### ISSUE TITLE
Use bedrock.account APIs when interacting with accounts

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-authn-token#10]
I think that the fact that this module interacts directly with the `accounts` mongodb collection is problematic.

Making changes to the data model internal to bedrock accounts would not normally constitute a breaking change, but there would be breakage here if for instance the name of the `accounts` collection were changed or similar.

**Comment by mattcollier** [comment]
@dlongley do you have thoughts about this?  I feel that this is something of a priority concern.

**Comment by dlongley** [comment]
So we should do this, but it's an internal change that, in theory, won't result in anything breaking (at least in the near term). It's a lower priority than other things that are needed to get this/other modules into shape. So I see it as more of a maintenance/technical debt concern than say, a security one.

**Comment by dlongley** [comment]
Fixed by #61.
