### ISSUE TITLE
Could change token hash to an HMAC w/key in SSM or HSM to increase security

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-authn-token#3]

**Comment by mattcollier** [comment]
@dlongley is this something we need to prioritize?

**Comment by dlongley** [comment]
We should, but not over a number of other things. If we have, for example, P1-P3 for things that we want to do in the near term, this is like P2.5. If it slips we'll be ok, but it will be more frustrating to upgrade later.

**Comment by dlongley** [comment]
The path to implementing this might involve breaking some tokenizer pieces off of bedrock-tokenization for reuse here. The general primitive needed is an auto-rotating tokenizer (which maps to a webkms hmac) that can be used to hmac authentication tokens. This would add an additional layer of security in the event of a stolen database -- and we could remove the prefixed hash that is currently used instead.

**Comment by dlongley** [comment]
This would also remove the need for using bcrypt to generate nonces on the server, further mitigating other threats.

**Comment by dlongley** [comment]
Instead of doing this, consider using SRP instead ([RFC 2945](https://datatracker.ietf.org/doc/html/rfc2945)) now that SRP patent has expired (actually expired 2015 but originally was going to expire in 2018 [link](https://en.wikipedia.org/wiki/Secure_Remote_Password_protocol)). There's an updated SRP version 6a mentioned in that last link.

Matthew Green [recommends using OPAQUE over SRP](https://blog.cryptographyengineering.com/should-you-use-srp/) so this should be investigated as well.

**Comment by dlongley** [comment]
Consider using a Halting KDF as a component of the system if needed (note: HKDF here is not HMAC KDF but Halting KDF) [link](https://www.researchgate.net/publication/234793871_Halting_password_puzzles_Hard-to-break_encryption_from_human-memorable_keys). If we do need an iterative hashing function this approach hides the number of iterations.

**Comment by dlongley** [comment]
We should ensure that we're not using bcrypt/scrypt for sufficiently large (128-bit) randomly generated nonce/challenges, it doesn't add any value. We only need to consider bcrypt/scrypt for human-readable smaller values that need "key stretching" of this sort.

**Comment by dlongley** [comment]
#51 is related to the above comment: https://github.com/digitalbazaar/bedrock-authn-token/issues/3#issuecomment-919558836

**Comment by dlongley** [comment]
It may be best to replace bcrypt with PBKDF2 because it has a native implementation on every client (where it matters).

**Comment by dlongley** [comment]
There are viable wasm builds of argon2: https://www.npmjs.com/package/argon2-browser
(and native-builds: https://www.npmjs.com/package/argon2)

Side note: Yes, `scrypt` is available in node.js (builtin: https://nodejs.org/api/crypto.html#cryptoscryptpassword-salt-keylen-options-callback), and JS (https://github.com/ricmoo/scrypt-js), but the memory demands it places on the server are a DoS concern.

**Comment by dlongley** [comment]
The decision here is to use PBKDF2 because of native, built-in support in clients.

**Comment by dlongley** [comment]
Addressed by #54.
