### ISSUE TITLE
Consider making `verify` return `false` when token not found

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-authn-token#9]
We may want to simply fail verification when a token is not found instead of returning not found. We should consider whether or not this is a serious concern for our threat model.

**Comment by mattcollier** [comment]
@dlongley priority?

**Comment by dlongley** [comment]
I think there are much higher priority items than this. I would think that this is something that could also be changed over time as an enhancement without causing too much trouble (if we decide it is necessary).

**Comment by dlongley** [comment]
Closing as unnecessary at this time.
